--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scotty-crud-deployment
  namespace: scotty-dev
  labels:
    app: scotty-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scotty-crud
  template:
    metadata:
      labels:
        app: scotty-crud
    spec:
      containers:
      - name: scotty-crud-container
        image: tusharknight8/scotty-crud:7.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
