---
apiVersion: v1
kind: Service
metadata:
  name: scotty-crud-service
  namespace: scotty-dev
spec:
  selector:
    app: scotty-crud
  ports:
    - port: 3001
      targetPort: 3001
  type: LoadBalancer
